// examples/vue-index-route/src/pages/book-list/index.vue
<template>
  <div>
    <h4>Book List</h4>
    <ul>
      <li>
        <router-link to="/books/The Old Man and the Sea">
          《The Old Man and the Sea》
        </router-link>
      </li>
      <li>
        <router-link to="/books/The adventures of Robinson Crusoe">
          《The adventures of Robinson Crusoe》
        </router-link>
      </li>
    </ul>

    <h4>Book Detail</h4>

    <div>
      <router-outlet />
    </div>
  </div>
</template>

// examples/react-index-route/src/pages/book-list/index.tsx
import { Link, Outlet } from 'oh-router-react'

export const BookListPage = () => {
  return (
    <div>
      <h4>Book List</h4>
      <ul>
        <li>
          <Link to="/books/The Old Man and the Sea">
            《The Old Man and the Sea》
          </Link>
        </li>
        <li>
          <Link to="/books/The adventures of Robinson Crusoe">
            《The adventures of Robinson Crusoe》
          </Link>
        </li>
      </ul>

      <h4>Book Detail</h4>

      <div>
        <Outlet />
      </div>
    </div>
  )
}
