// examples/vue-middlewares/src/pages/login/index.vue
<template>
  <div>
    <input placeholder="name" v-model="name" />
    <button @click="onLogin">login</button>
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue'
import { router } from '../../router'

const name = ref('')

const onLogin = () => {
  if (!name.value) {
    alert('Name cannot be empty')
    return
  }
  localStorage.setItem('user', name.value)
  router.navigate('/')
}
</script>

// examples/react-middlewares/src/pages/login/index.tsx
import { useState } from 'react'
import { router } from '../../router'

export const LoginPage = () => {
  const [name, setName] = useState('')

  const onLogin = () => {
    if (!name) {
      alert('Name cannot be empty')
      return
    }
    localStorage.setItem('user', name)
    router.navigate('/')
  }

  return (
    <div>
      <input placeholder="name" onChange={(e) => setName(e.target.value)} />
      <button onClick={onLogin}>login</button>
    </div>
  )
}
