// examples/react-middlewares/src/pages/home/index.tsx
import { router } from '../../router'

export const HomePage = () => {
  const user = localStorage.getItem('user')

  const onLogout = () => {
    localStorage.removeItem('user')
    router.navigate('/login')
  }

  return (
    <div>
      <div>
        Hi {user}! <button onClick={onLogout}>logout</button>
      </div>
    </div>
  )
}

// examples/vue-middlewares/src/pages/home/index.vue
<template>
  <div>
    <div>Hi {{ user }}! <button @click="onLogout">logout</button></div>
  </div>
</template>

<script lang="ts" setup>
import { router } from '../../router'

const user = localStorage.getItem('user')

const onLogout = () => {
  localStorage.removeItem('user')
  router.navigate('/login')
}
</script>
