// examples/react-nested-routes/src/layout/base.tsx
import { Link, Outlet } from 'oh-router-react'
import { FC } from 'react'

export const BaseLayout: FC = () => {
  return (
    <div className="index">
      <div style={{ padding: 8 }}>
        <Outlet />
      </div>

      <div
        style={{
          position: 'fixed',
          bottom: 0,
          left: 0,
          right: 0,
          height: 50,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-around',
          borderTop: '1px solid #dfdfdf',
        }}
      >
        <Link to="/">Home</Link>|<Link to="/about">About</Link>
      </div>
    </div>
  )
}

// examples/vue-nested-routes/src/layout/base.vue
<template>
  <div>
    <div class="container">
      <router-outlet />
    </div>

    <div class="navBar">
      <router-link to="/">Home</router-link> |
      <router-link to="/about">About</router-link>
    </div>
  </div>
</template>

<style scoped>
.container {
  padding: 8px;
}

.navBar {
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  height: 50px;
  display: flex;
  align-items: center;
  justify-content: space-around;
  border-top: 1px solid #dfdfdf;
}
</style>
